<?php

namespace SA\MuseumBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function TicketsNbrByDate($bookedday)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->where('t.bookedday = :bookedday')
           ->setParameter('bookedday', $bookedday);

        $value = $qb
            ->getQuery()
            ->getSingleScalarResult();

        return $value;
    }
}
